version : "3.9"

services:
  goapi:
    container_name: goapi
    image: goapi
    build: .
    restart: on-failure
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - pgsql
    networks:
      - apinetwork

  pgsql:
    image: postgres:12
    container_name: pgsql
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - pgsqldata:/var/lib/postgresql/data
    networks:
      - apinetwork

volumes:
  pgsqldata: {}

networks:
  apinetwork:
    driver: bridge
